version: 2.1

orbs:
  node: circleci/node@1.1.6
jobs:
  lint-and-test:
    executor:
      name: node/default
    steps:
      - checkout
      - node/with-cache:
          steps:
            - run: yarn
            - run: yarn lint
            - run: yarn test
workflows:
  lint-and-test:
    jobs:
      - lint-and-test
